#!/usr/bin/env bash
#Prints the contents of the /etc/passwd file with a while loop
#and only displays fields 1, 3 and 6
file="/etc/passwd"
while read -r line;
do
	echo "$line" | cut -d':' -f1,3,6
done <"$file"
