#!/usr/bin/env bash
#Write a Bash script that displays the content of the file

file="/etc/passwd"
while IFS=':' read -r F1 F2 F3 F4 F5 F6 F7;
do
    echo "The user $F1 is part of the $F4 gang, lives in $F6 and rides $F7. $F3's place is protected by the passcode $F2, more info about the user here: $F5"

done <"$file"
