#!/usr/bin/env bash
# Bash script that loops from 1 to and and displays 'bad luck' for the 4th loop
# iteration, 'good luck' for the 8th loop iteration, and Holberton School
# for the other iterations
i=0
while((i<10));
do
	if((i==3));
	then
		echo bad luck
	elif((i==7));
	then
		echo good luck
	else
		echo Holberton School
	fi
	i=$((i+1))
done
