#!/usr/bin/env bash
#Prints 1-20 to stdout using a while loop.
#Prints something unique on the 4th, 9th and 17th iterations
n=1
while ((n < 21));
do
	echo $n
	case "$n" in
		4) echo bad luck from China ;;
		9) echo bad luck from Japan ;;
		17) echo bad luck from Italy ;;
	esac
	n=$((n+1))
done
