#!/usr/bin/env bash
# Restart nginx running as user nginx on 8080
chmod 744 /etc/nginx/nginx.conf
sudo pkill apache2
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx start
